### ISSUE TITLE
Loading Failed

### ISSUE THREAD

**Issue by karsonatorz** [Hawkite/steam-account-manager#4]
Hi, I am getting this error when I attempt to install via your instructions. I don't understand what's wrong but this program seems pretty nice, I'd like to use it. Could you help?

[karsonatorz@asdfg steam-account-manager]$ npm start

> steam-account-manager@1.0.0 start /home/karsonatorz/shit/steam-account-manager
> electron .

App threw an error during load
Error: Cannot find module 'steam-user'
Require stack:
- /home/karsonatorz/shit/steam-account-manager/index.js
- /usr/lib/electron/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/karsonatorz/shit/steam-account-manager/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'steam-user'
Require stack:
- /home/karsonatorz/shit/steam-account-manager/index.js
- /usr/lib/electron/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/karsonatorz/shit/steam-account-manager/index.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)

(electron:24977): Gtk-WARNING **: 10:54:51.161: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Gtk-Message: 10:54:51.178: Failed to load module "appmenu-gtk-module"
^C

**Comment by Hawkite** [comment]
Hello, have you tried doing `npm install` before running `npm start`?

You can also go to the *releases* tab on the project page and download the zip file, once unzipped the folder will contain the EXE that has everything already installed and ready to run. I have not updated the readme to reflect this (more streamlined) method but this should be the solution if the above does not work. 

Please close this issue if I have solved your problem. Thank you.
